# Form implementation generated from reading ui file 'graphics.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 435)
        MainWindow.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pages = QtWidgets.QTabWidget(parent=self.centralwidget)

        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setKerning(True)

        self.pages.setFont(font)
        self.pages.setStyleSheet(
        """
        QTabWidget::pane { background-color: rgb(30, 30, 30); }

        QTabBar::tab:selected {
                background-color: #FF5500;
                color: #414141;
                border-radius: 5px;
                padding: 10px;
                width: 100px;
        }
        QTabBar::tab:!selected {
                background-color: #414141;
                color: #FF5500;
                border-radius: 5px;
                padding: 10px;
                width: 100px;
        }
        QTabBar::tab:hover { background-color: #2ABf9E; color: #414141}
        QTabBar::tab:pressed {
                border-width: 1px;
                border-style: solid;
                border-color: rgb(160, 160, 160);
        }

        """
)

        self.pages.setObjectName("pages")

        self.record_page = QtWidgets.QWidget()
        self.record_page.setStyleSheet(
        """
        QWidget {color: rgb(255, 85, 0); background-color: rgb(65, 65, 65); border-radius: 5px;}

        QPushButton {
                border-radius: 20px;
                margin: 10px;
                border-width: 2px;
                border-style: solid;
                border-color: rgb(160, 160, 160);
        }
        QPushButton:hover { background-color: rgb(255, 100, 100); color: #414141}
        QPushButton:pressed {border-color: rgb(255, 255, 255);}
        
        QLabel {background-color: rgb(30, 30, 30);}
        """
)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(20)
        self.record_page.setFont(font)
        self.record_page.setObjectName("record_page")

        self.gridLayout_4 = QtWidgets.QGridLayout(self.record_page)
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.record_frame = QtWidgets.QFrame(parent=self.record_page)
        self.record_frame.setObjectName("record_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.record_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.record_button = QtWidgets.QPushButton(parent=self.record_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_button.sizePolicy().hasHeightForWidth())
        self.record_button.setSizePolicy(sizePolicy)
        self.record_button.setFont(font)
        self.record_button.setObjectName("record_button")
        self.gridLayout_3.addWidget(self.record_button, 2, 0, 1, 1)

        self.stop_button = QtWidgets.QPushButton(parent=self.record_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_3.addWidget(self.stop_button, 2, 1, 1, 1)

        self.save_button = QtWidgets.QPushButton(parent=self.record_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.gridLayout_3.addWidget(self.save_button, 2, 2, 1, 1)

        self.record_label = QtWidgets.QLabel(parent=self.record_frame)
        self.record_label.setFont(font)
        self.record_label.setTabletTracking(False)
        self.record_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.record_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.record_label.setObjectName("record_label")
        self.gridLayout_3.addWidget(self.record_label, 0, 0, 1, 3)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.record_frame, 0, 0, 1, 1)

        self.pages.addTab(self.record_page, "")
        self.play_page = QtWidgets.QWidget()
        self.play_page.setStyleSheet("color: rgb(255, 85, 0); background-color: rgb(65, 65, 65); border-radius: 10px")
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.play_page.setFont(font)
        self.play_page.setStyleSheet(
        """
        QWidget {color: rgb(255, 85, 0); background-color: rgb(65, 65, 65); border-radius: 5px;}

        QPushButton {
                border-radius: 5px;
                margin: 10px;
                border-width: 2px;
                border-style: solid;
                border-color: rgb(160, 160, 160);
                padding: 10px;
        }

        QLabel {
                padding: 20px;
        }

        QPushButton:hover { background-color: rgb(255, 100, 100); color: #414141}
        QPushButton:pressed {border-color: rgb(255, 255, 255)}

        QLineEdit {
                background-color: rgb(30, 30, 30);
        }

        QSpinBox {background-color: rgb(30, 30, 30);}

        """
)
        self.play_page.setObjectName("play_page")

        self.gridLayout_5 = QtWidgets.QGridLayout(self.play_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.play_frame = QtWidgets.QFrame(parent=self.play_page)
        
        self.play_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.play_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.play_frame.setObjectName("play_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.play_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 2)
        self.iteration_label = QtWidgets.QLabel(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iteration_label.sizePolicy().hasHeightForWidth())
        self.iteration_label.setSizePolicy(sizePolicy)
        self.iteration_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.iteration_label.setFont(font)
        self.iteration_label.setObjectName("iteration_label")
        self.gridLayout_2.addWidget(self.iteration_label, 3, 0, 1, 1)

        self.file_record_button = QtWidgets.QPushButton(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_record_button.sizePolicy().hasHeightForWidth())
        self.file_record_button.setSizePolicy(sizePolicy)
        self.file_record_button.setFont(font)
        self.file_record_button.setObjectName("file_record_button")
        self.gridLayout_2.addWidget(self.file_record_button, 2, 0, 1, 1)

        self.get_button = QtWidgets.QPushButton(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_button.sizePolicy().hasHeightForWidth())
        self.get_button.setSizePolicy(sizePolicy)
        self.get_button.setFont(font)
        self.get_button.setObjectName("get_button")
        self.gridLayout_2.addWidget(self.get_button, 0, 0, 1, 1)

        self.get_edit = QtWidgets.QLineEdit(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_edit.sizePolicy().hasHeightForWidth())
        self.get_edit.setSizePolicy(sizePolicy)
        self.get_edit.setFont(font)
        self.get_edit.setClearButtonEnabled(False)
        self.get_edit.setObjectName("get_edit")
        self.gridLayout_2.addWidget(self.get_edit, 0, 1, 1, 1)

        self.iteration_spin_box = QtWidgets.QSpinBox(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iteration_spin_box.sizePolicy().hasHeightForWidth())
        self.iteration_spin_box.setSizePolicy(sizePolicy)
        self.iteration_spin_box.setFont(font)
        
        self.iteration_spin_box.setObjectName("iteration_spin_box")
        self.gridLayout_2.addWidget(self.iteration_spin_box, 3, 1, 1, 1)

        self.play_button = QtWidgets.QPushButton(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setFont(font)
        self.play_button.setStyleSheet("height: 80px; font-size: 30px ")
        self.play_button.setObjectName("play_button")
        self.gridLayout_2.addWidget(self.play_button, 6, 0, 1, 2)

        self.file_record_edit = QtWidgets.QLineEdit(parent=self.play_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_record_edit.sizePolicy().hasHeightForWidth())
        self.file_record_edit.setSizePolicy(sizePolicy)
        self.file_record_edit.setFont(font)
        self.file_record_edit.setObjectName("file_record_edit")
        self.gridLayout_2.addWidget(self.file_record_edit, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.play_frame, 0, 0, 1, 1)
        
        self.pages.addTab(self.play_page, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pages.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.pages, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automation"))
        self.record_button.setText(_translate("MainWindow", "Record"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.stop_button.setShortcut(_translate("MainWindow", "Esc"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.record_label.setText(_translate("MainWindow", "Not recorded yet"))
        self.pages.setTabText(self.pages.indexOf(self.record_page), _translate("MainWindow", "Record"))
        self.iteration_label.setText(_translate("MainWindow", "Iteration"))
        self.file_record_button.setText(_translate("MainWindow", "File Record"))
        self.get_button.setText(_translate("MainWindow", "Get"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.pages.setTabText(self.pages.indexOf(self.play_page), _translate("MainWindow", "Play"))
        self.pages.setTabText(self.pages.indexOf(self.tab_3), _translate("MainWindow", "Tutorial"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())